apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache
spec:
  selector:
    app: apache
  ports:
  - protocol: TCP
    port: 80          # service port (recommended)
    targetPort: 80
    nodePort: 30080   # external port
  type: NodePort
